name: Build adfmaker for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v3

    - name: Rust Kurulumu
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Release Derlemesi
      run: cargo build --release

    - name: Çıktıyı Yükle
      uses: actions/upload-artifact@v4
      with:
        name: adfmaker-exe
        path: target/release/adfmaker.exe
