name: Build Rust Project (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build release
      run: cargo build --release

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: rust-exe
        path: target/release/*.exe
